app/usuarios/models.py
from app import db
from sqlalchemy import ForeignKey

from app.sociosActividad.models import Socioactividad

from ..actividades.models import Actividad
from ..deudas.models import Deuda


class Usuario(db.Model):
    Id = db.Column(db.Integer, primary_key=True)
    Nombre = db.Column(db.String(100), nullable=False)
    Contrasenia = db.Column(db.String(200), nullable=False)
    Id_socio = db.Column(db.Integer, ForeignKey('socio.Id'))
    Id_tipousuario = db.Column(db.Integer, ForeignKey('tipousuario.Id'))
    Fcarga = db.Column(db.Date, nullable=False)

    def __init__(self, Nombre, Contrasenia, Id_socio, Id_tipousuario, Fcarga):
        self.Nombre = Nombre
        self.Contrasenia = Contrasenia
        self.Id_socio = Id_socio
        self.Id_tipousuario = Id_tipousuario
        self.Fcarga = Fcarga

    def __repr__(self):
        return self.Nombre

    def get_deudas(self):
        return Deuda.query.filter_by(Id_socio=self.Id_socio)

    def get_active(self):
        return Deuda.query.filter_by(Id_socio=self.Id_socio, Abonada=0)

    def get_billed(self):
        return Deuda.query.filter_by(Id_socio=self.Id_socio, Abonada=1)

    def get_actividades(self):
        return Socioactividad.query.filter_by(Activo=1, Id_socio=self.Id_socio).all()

    def get_by_name(username):
        return Usuario.query.filter_by(Nombre=username).one()

    # EL SALT GENERADO EN LOGIN SIEMPRE ES DISTINTO, NO MATCHEA
    # def auth(usr, pwd):
    #     return Usuario.query.filter_by(Nombre=usr, Contrasenia=pwd).one()

    def get_by_id(id):
        return Usuario.query.filter_by(Id=id).one()


class Tipousuario(db.Model):
    Id = db.Column(db.Integer, primary_key=True)
    Nombre = db.Column(db.String(100), nullable=False)
    Descripcion = db.Column(db.String(200), nullable=False)

    def __init__(self, Nombre, Descripcion):
        self.Nombre = Nombre
        self.Descripcion = Descripcion

    def __repr__(self):
        return '<%r>' % self.Nombre

app/usuarios/__init__.py
from flask import Blueprint

usuarios_bp = Blueprint('usuarios', __name__, template_folder='templates')

# NO BORRAR vvvv
from . import controllers

app/usuarios/controllers.py
from flask import render_template, request, url_for, jsonify, flash, session, g, abort
import decimal
import bcrypt
from werkzeug.utils import redirect
from app.actividades.models import Actividad

from app.deudas.models import Deuda
from app.familias.models import Familiar
from app.personas.models import Persona
from app.socios.models import Socio
from app.usuarios.decorator import auth_required
from .models import Usuario, Tipousuario
from .schemas import usuario_schema, tipousuario_schema
from app import db

from . import usuarios_bp


@usuarios_bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        session.pop('user_id', None)
        username = request.form['username']
        password = request.form['password']

        try:
            user = Usuario.get_by_name(username)
            if user.Contrasenia == password:
                session['user_id'] = user.Id
                flash(
                    f"Bienvenido {user}", "success")
                flash('Por favor cambie su contrasenia', "warning")
                return redirect(url_for('usuarios.change_password'))
            else:
                if bcrypt.checkpw(password.encode('utf-8'), user.Contrasenia.encode('utf-8')):
                    session['user_id'] = user.Id
                    flash(
                        f"Bienvenido {user}", "success")
                    return redirect(url_for('index'))
                3/0  # ERROR PARA SALIR POR EXCEPT
        except:
            flash(
                f"Usuario o contraseña incorrectos, vuelva a intentar", "danger")
            return redirect(url_for('usuarios.login'))

    return render_template("usuarios/login.html")


@usuarios_bp.route("/logout")
def logout():
    session.pop('user_id', None)
    flash(
        "Cierre de Sesión", "success")

    return redirect(url_for('index'))


@usuarios_bp.route("/password", methods=['GET', 'POST'])
def change_password():
    if not g.user:
        abort(401)
    if request.method == 'POST':
        password = request.form['nuevapass'].encode('utf-8')
        user = Usuario.get_by_id(g.user.Id)
        hashPwd = bcrypt.hashpw(password, bcrypt.gensalt(12))
        user.Contrasenia = hashPwd
        db.session.commit()
        return redirect(url_for('index'))

    return render_template(('usuarios/cambiar_contrasenia.html'))


@usuarios_bp.route("/")
def index():
    if not g.user:
        abort(401)
    deuda_todos = Usuario.get_deudas(g.user)
    socio = Socio.get_all()
    persona = Persona.get_all()

    return render_template("usuarios/deudasSocio.html", deudas=deuda_todos, socios=socio, personas=persona)


@usuarios_bp.route("/abonados")
def abonados():
    if not g.user:
        abort(401)
    deuda_abonados = Usuario.get_billed(g.user)
    socio = Socio.get_all()
    persona = Persona.get_all()

    return render_template("usuarios/deudasSocio.html", deudas=deuda_abonados, socios=socio, personas=persona)


@usuarios_bp.route("/activos")
def activos():
    if not g.user:
        abort(401)
    deuda_activos = Usuario.get_active(g.user)
    socio = Socio.get_all()
    persona = Persona.get_all()

    return render_template("usuarios/deudasSocio.html", deudas=deuda_activos, socios=socio, personas=persona)


@usuarios_bp.route("/perfil")
def profile():
    if not g.user:
        abort(401)
    socio = Socio.get_by_id(g.user.Id_socio)
    cliente = Persona.get_by_id(socio.Id_persona)
    actividades = Usuario.get_actividades(g.user)
    listact = Actividad.get_all()
    familiares = Familiar.get_socio(g.user.Id_socio)
    personas = Persona.get_all()

    return render_template("usuarios/perfil.html", cliente=cliente, actividades=actividades, listact=listact, familiares=familiares, personas=personas)

app/usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends "base_template.html" %}

{% block title %}{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center h-100">
        <div class="card col-md-5 border rounded" style="background-color: rgb(175, 183, 224);">
            <div class="card-header mt-2 border-0">
                <h3 class="text-center font-weight-bold">Cambiar Contraseña</h3>
            </div>
            <div class="card-body mt-3">
                <form method="POST">
                    <div class="input-group form-group col-md-10 offset-md-1 mb-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-warning"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" class="form-control" name="nuevapass"
                            placeholder="Ingrese su nueva Contraseña" required>
                    </div>
                    <div class="form-group text-center">
                        <input type="submit" value="Login" class="btn btn-warning col-md-3">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/usuarios/templates/usuarios/deudasSocio.html
{% extends "base_template.html" %}

{% block title %}Deudas{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        <a class="btn btn-primary btn-lg mr-1 " href='{{ url_for("usuarios.index") }}'>
            Todas
        </a>
        <a class="btn btn-primary btn-lg mr-1" href='{{ url_for("usuarios.abonados") }}'>
            Pagadas
        </a>
        <a class="btn btn-primary btn-lg" href='{{ url_for("usuarios.activos") }}'>
            Pendientes
        </a>
        <div class="btn-group float-right" role="group">
            <a class="btn btn-primary btn-lg" href='{{ url_for("usuarios.profile") }}'>
                Mi Perfil
            </a>
        </div>
    </div>
</div>
<br>

<table style="width:100%" class="table table-dark table-hover table-bordered mt-3 display nowrap" cellspacing="0"
    id="myTable">
    <thead class="text-center">
        <tr>
            <th>Socio</th>
            <th>Descripcion</th>
            <th>Importe</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        {%for deuda in deudas%}
        <tr class="text-center text-dark table-secondary">
            {% for socio in socios%}
            {%if socio.Id == deuda.Id_socio%}
            {%for persona in personas%}
            {%if persona.Id == socio.Id_persona%}
            <td class="text-left">{{persona.Nombre}}</td>
            {%endif%}
            {%endfor%}
            {%endif%}
            {%endfor%}
            <td>{{deuda.Descripcion}} | {{deuda.Mes.strftime('%Y-%m-%d')}}</td>
            <td>{{deuda.Importe}}</td>
            {% if deuda.Abonada == 1 %}
            <td> Pagada </td>
            {% else %}
            <td> Se debe </td>
            {%endif%}
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th id="num1" class="text-center"></th>

            <!--aca se muestra la suma total de deudas-->
        </tr>
    </tfoot>
</table>

<script>
    //Filtros columnas
    $(document).ready(function () {
        var table = $('#myTable').DataTable({
            "dom": 'Blfrtip',
            //"lengthMenu": [[12, 25, 50, -1], [12, 25, 50, "Todos"]],            
            paging: false,
            lengthChange: false,
            pageLength: -1,
            orderCellsTop: true,
            scrollY: 525,
            scrollX: true,
            "order": [[1, "desc"]],
            "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json" },
            "drawCallback": function () { //calcula el total de una columna cada vez que se "dibuja"
                var api = this.api();
                var total = api.column(2, { page: 'current' }).data().sum().toFixed(2)
                $(api.column(0).footer()).html(
                    'Total: $ ' + total
                )
            },
            buttons: [
                {
                    extend: 'print',
                    text: '<i class="fa fa-print"> Imprimir</i>',
                    titleAttr: 'Imprimir',
                    className: 'btn btn-info',
                    autoPrint: true,
                    messageTop: function () { // trae el query
                        var query = table.search()
                        if (query) {
                            return '<h3 class="text-center mt-3">Deudas ("' + query + '")</h3>'
                        }
                        else {
                            return '<h3 class="text-center mt-3">Deudas</h3>'
                        }
                    },
                    messageBottom: function () { // calcula el total 
                        var total = table.column(2, { page: 'current' }).data().sum().toFixed(2)
                        return '<h4 class="text-center mt-3">Total: $' + total + '</h4>'
                    },
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    },
                    customize: function (win) {
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .removeClass('table-hover')
                            .css('font-size', 'inherit')
                    }
                },
                {
                    extend: 'pdfHtml5',
                    text: '<i class="fa fa-file-pdf"> PDF</i>',
                    titleAttr: 'Exportar a PDF',
                    className: 'btn btn-danger',
                    footer: true,
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    },
                }
            ]
        });
    });
</script>
{% endblock %}

app/usuarios/templates/usuarios/login.html
{% extends "base_template.html" %}

{% block title %}Actividades{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center h-100">
        <div class="card col-md-5 border rounded" style="background-color: rgb(175, 183, 224);">
            <div class="card-header mt-2 border-0">
                <h3 class="text-center font-weight-bold">Iniciar Sesión</h3>
            </div>
            <div class="card-body mt-3">
                <form method="POST">
                    <div class="input-group form-group col-md-10 offset-md-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-warning"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" name="username" placeholder="Usuario" required>
                    </div>
                    <div class="input-group form-group col-md-10 offset-md-1 mb-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-warning"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" class="form-control" name="password" placeholder="Contraseña" required>
                    </div>
                    <div class="form-group text-center">
                        <input type="submit" value="Login" class="btn btn-warning col-md-3">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/usuarios/templates/usuarios/perfil.html
{% extends "base_template.html" %}

{% block title %}Deudas{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        <div class="btn-group float-right" role="group">
            <a class="btn btn-primary btn-lg mr-1 " href='{{url_for("usuarios.index")}}'>
                Mis Deudas
            </a>
            <a class="btn btn-primary btn-lg mr-1 " href='{{url_for("usuarios.change_password")}}'>
                Cambiar Contraseña
            </a>
        </div>
    </div>
</div>
<br>
<h3 class="text-left">Mis Datos</h3>
<table style="width:100%" class="table table-dark table-hover table-bordered mt-3 display nowrap">
    <thead class="text-center">
        <th scope="col">Nombre</th>
        <th scope="col">DNI</th>
        <th scope="col">Fecha de Nacimiento</th>
        <th scope="col">Sexo</th>
    </thead>
    <tbody>
        <tr class="text-center text-dark table-secondary">
            <td>{{cliente.Nombre}}</td>
            <td>{{cliente.Dni}}</td>
            <td>{{cliente.Fnacimiento.strftime('%d-%m-%Y')}}</td>
            {% if cliente.Sexo == 1 %}
            <td> Masculino </td>
            {% else %}
            <td> Femenino </td>
            {%endif%}
        </tr>
    </tbody>
</table>
<br>
<h3 class="text-left">Mis Actividades</h3>
<table class="table table-dark table-hover table-bordered mt-3 display nowrap">
    <thead class="text-center">
        <th scope="col">Actividad</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Valor</th>
    </thead>
    <tbody>
        {%for actividad in actividades%}
        <tr class="text-dark table-secondary text-center">
            {%for act in listact%}
            {% if actividad.Id_actividad == act.Id%}
            <td class="text-left">{{act.Nombre}}</td>
            <td>{{act.Descripcion}}</td>
            <td>{{act.Valor}}</td>
            {%endif%}
            {%endfor%}
        </tr>
        {%endfor%}
    </tbody>
</table>
<br>
<h3 class="text-left">Mi Familia</h3>
<table style="width:100%" class="table table-dark table-hover table-bordered mt-3 display nowrap">
    <thead>
        <th scope="col">Nombre</th>
    </thead>
    <tbody>
        {%for familiar in familiares %}
        <tr class="text-center text-dark table-secondary">
            {%for persona in personas%}
            {%if persona.Id == familiar.Id_persona%}
            <td class="text-left">{{persona.Nombre}}</td>
            {%endif%}
            {%endfor%}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}